default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_list_service_development

test:
  <<: *default
  database: todo_list_service_test

production:
  <<: *default
  database: todo_list_service_production
  username: todo_list_service
  password: <%= ENV['TODO_LIST_SERVICE_DATABASE_PASSWORD'] %>